version: "3.9"
services:
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /app/resources/initial_data/realm_export.json
    volumes:
      - "${PWD}:/app:ro"