version: "3.9"
services:
  keycloak:
    image: jboss/keycloak:12.0.4
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /app/resources/initial_data/realm-export.json
    volumes:
      - "${PWD}:/app:ro"
  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - "27017:27017"